services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8321:8000"
    volumes:
      - chromadb_data:/data
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/data
      - ANONYMIZED_TELEMETRY=FALSE
      - ALLOW_RESET=true
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=*
    networks:
      - ai_network
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=2
    networks:
      - ai_network
    restart: unless-stopped

  chromadb-admin:
    image: renl/chromadb-admin:latest
    container_name: chromadb_admin_ui
    ports:
      - "8322:8322"
    environment:
      NEXT_PUBLIC_CHROMADB_API_HOST: "http://chromadb:8000"
    depends_on:
      - chromadb
    networks:
      - ai_network
    restart: unless-stopped



networks:
  ai_network:
    driver: bridge

volumes:
  chromadb_data:
    name: chromadb_data
  ollama_models:
    name: ollama_models